### ISSUE TITLE
wrong calculation in siamese loss

### ISSUE THREAD

**Issue by mzy97** [Medabid1/TravelGAN#1]
x1 is the image batch with size (batch_num,channel,w,h)
you use x1.size(0) = batch =_num to get the combination do you mean 1024 in this position?

https://github.com/Medabid1/TravelGAN/blob/70542c67fbc7884e4a919652edb23cc02fead046/src/modules.py#L139

and addition, wrong combination will cause 
`v1 = latent1[pairs[:, 0]] - latent1[pairs[:, 1]]` 
not working

**Comment by zjy9779** [comment]
Why has my data never been read, the path has changed

**Comment by Medabid1** [comment]
@mzy97 , i use the batch size, coz ou should compare images in the same batch to compute the distance. 
![image](https://user-images.githubusercontent.com/30070233/84065020-9e55da00-a991-11ea-9977-66499dc2be39.png)

**Comment by Medabid1** [comment]
@zjy9779 , what do you mean ?

**Comment by zjy9779** [comment]
Why is my siamese loss always negative?

**Comment by Medabid1** [comment]
the model needs to maximize the Travel loss, which is equal to minimize minus Travel loss. The travel loss cause the Siamese loss to be negative

**Comment by mzy97** [comment]
> the model needs to maximize the Travel loss, which is equal to minimize minus Travel loss. The travel loss cause the Siamese loss to be negative

@Medabid1 But in the paper, it said the Travel loss should be minimized, why you said it needs to maximize? Can you give a detail explanation of why siamese loss sometime negtive?

<img width="585" alt="image" src="https://user-images.githubusercontent.com/31816690/84584606-0cd6e400-ae39-11ea-9f13-f6f09a7c8410.png">

<img width="571" alt="image" src="https://user-images.githubusercontent.com/31816690/84584623-33951a80-ae39-11ea-854d-7674457e2d3a.png">

**Comment by mzy97** [comment]
Another question, in your loss computation, mse is positive number, minus cos_similarity may gernerate negtive number when angle < 90degree, will the negtive loss affect training process? Thank you
<img width="735" alt="image" src="https://user-images.githubusercontent.com/31816690/84584743-a18e1180-ae3a-11ea-949e-952324e95731.png">

**Comment by Medabid1** [comment]
> 
> 
> > the model needs to maximize the Travel loss, which is equal to minimize minus Travel loss. The travel loss cause the Siamese loss to be negative
> 
> @Medabid1 But in the paper, it said the Travel loss should be minimized, why you said it needs to maximize? Can you give a detail explanation of why siamese loss sometime negtive?
> 
> <img alt="image" width="585" src="https://user-images.githubusercontent.com/31816690/84584606-0cd6e400-ae39-11ea-9f13-f6f09a7c8410.png">
> 
> <img alt="image" width="571" src="https://user-images.githubusercontent.com/31816690/84584623-33951a80-ae39-11ea-854d-7674457e2d3a.png">

ah yes, i was wrong, yes the travel loss needs to be minimized. here we minimize the distance between the latent vectors. That s is done by making the sure that their norms are equal and they have the same angle. that s the distance loss 
![image](https://user-images.githubusercontent.com/30070233/84686285-aa99e400-af09-11ea-8ce7-e3aacf8d2ae1.png). i don t think the negative loss affect the training.

**Comment by gdwei** [comment]
In their paper, they suggest the use of cos similarity, so I think you do not need to constraint the norm.
The cos similarity loss should be 1-CosineSimilarity( , )
